// GENERATED by `make types` from contracts/shadeway_contracts/api.py.
// Do not edit by hand. `make test` fails if this file is out of date.

export interface LatLon {
  lat: number;
  lon: number;
}

export interface HeatProfile {
  name: string;
  minutes_per_degree: number;
}

export interface RouteRequest {
  origin: LatLon;
  destination: LatLon;
  depart_iso: string;
  profile: HeatProfile;
  walk_speed_ms: number;
  max_alternatives: number;
  time_dependent: boolean;
}

export interface WeatherSnapshot {
  observed_iso: string;
  air_temp_c: number;
  relative_humidity_pct: number;
  wind_speed_10m_ms: number;
  cloud_cover_pct: number;
  direct_normal_wm2: number;
  diffuse_wm2: number;
  global_horizontal_wm2: number;
  uv_index: number;
  source: string;
}

export interface FeelsLike {
  mean_c: number;
  max_c: number;
  p90_c: number;
}

export interface Exposure {
  sun_fraction: number;
  mean_svf: number;
  canopy_fraction: number;
}

export interface LegStep {
  edge_id: number;
  street_name: string;
  side: number;
  kind: number;
  geometry: [number, number][];
  length_m: number;
  enter_iso: string;
  exit_iso: string;
  feels_like_c: number;
  tmrt_c: number;
  f_sun: number;
  svf: number;
}

export interface InstructionWhy {
  sunlit_until_iso: string | null;
  shaded_by: string | null;
  delta_c: number | null;
  dappled: boolean;
}

export interface Instruction {
  type: string;
  at: LatLon;
  text: string;
  why: InstructionWhy | null;
}

export interface WaypointSuggestion {
  amenity_id: number;
  kind: number;
  name: string;
  at: LatLon;
  detour_s: number;
  inserted_after_leg: number;
}

export interface Route {
  route_id: string;
  label: string;
  depart_iso: string;
  arrive_iso: string;
  duration_s: number;
  distance_m: number;
  feels_like_c: FeelsLike;
  exposure: Exposure;
  legs: LegStep[];
  instructions: Instruction[];
  waypoints: WaypointSuggestion[];
}

export interface FrontierPoint {
  route_id: string;
  duration_s: number;
  mean_feels_like_c: number;
}

export interface RouteResponse {
  request_id: string;
  computed_at: string;
  weather: WeatherSnapshot;
  frontier: FrontierPoint[];
  routes: Record<string, Route>;
  chosen_route_id: string;
  cache_warm: boolean;
  compute_ms: number;
}

export interface TimeseriesPoint {
  at_iso: string;
  mean_feels_like_c: number;
  max_feels_like_c: number;
  sun_fraction: number;
}

export interface TimeseriesResponse {
  route_id: string;
  points: TimeseriesPoint[];
}

export interface DeparturePoint {
  depart_iso: string;
  best_mean_feels_like_c: number;
  best_duration_s: number;
}

export interface DepartureCurveResponse {
  points: DeparturePoint[];
  now_index: number;
  best_index: number;
}

export interface PlantRequest {
  positions: LatLon[];
  species: string;
  dbh_cm: number;
}

export interface PlantResponse {
  planted: number;
  invalidated_samples: number;
  scene_version: number;
}

export const PRESET_PROFILE_NAMES = ["standard", "sensitive", "high_risk"] as const;
