"""Generate `web/src/api/types.ts` from the pydantic models so the client type and the
server type cannot drift. Run via `make types`; `make test` fails if the file is stale."""

from __future__ import annotations

import argparse
import datetime as dt
import sys
import types as pytypes
import typing
from pathlib import Path

from pydantic import AwareDatetime, BaseModel

from shadeway_contracts import api

EXPORTED: list[type[BaseModel]] = [
    api.LatLon, api.HeatProfile, api.RouteRequest, api.WeatherSnapshot, api.FeelsLike,
    api.Exposure, api.LegStep, api.InstructionWhy, api.Instruction,
    api.WaypointSuggestion, api.Route, api.FrontierPoint, api.RouteResponse,
    api.TimeseriesPoint, api.TimeseriesResponse, api.DeparturePoint,
    api.DepartureCurveResponse, api.PlantRequest, api.PlantResponse,
]

HEADER = """// GENERATED by `make types` from contracts/shadeway_contracts/api.py.
// Do not edit by hand. `make test` fails if this file is out of date.

"""


def _ts_type(annotation: typing.Any) -> str:
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin in (typing.Union, pytypes.UnionType):
        return " | ".join(
            "null" if a is type(None) else _ts_type(a) for a in args
        )
    if origin in (list, tuple):
        if origin is tuple and len(args) > 1 and args[1] is not Ellipsis:
            return "[" + ", ".join(_ts_type(a) for a in args) + "]"
        return f"{_ts_type(args[0])}[]"
    if origin is dict:
        return f"Record<{_ts_type(args[0])}, {_ts_type(args[1])}>"
    if annotation in (str, dt.datetime, AwareDatetime) or annotation is api.ISO:
        return "string"
    if annotation is bool:
        return "boolean"
    if annotation in (int, float):
        return "number"
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    if annotation is typing.Any:
        return "unknown"
    raise TypeError(f"no TypeScript mapping for {annotation!r}")


def render_types() -> str:
    out = [HEADER]
    for model in EXPORTED:
        out.append(f"export interface {model.__name__} {{\n")
        for name, field in model.model_fields.items():
            out.append(f"  {name}: {_ts_type(field.annotation)};\n")
        out.append("}\n\n")
    out.append(
        "export const PRESET_PROFILE_NAMES = "
        + str(list(api.PRESET_PROFILES)).replace("'", '"')
        + " as const;\n"
    )
    return "".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_types()
    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current != rendered:
            print(f"{args.out} is stale — run `make types`", file=sys.stderr)
            raise SystemExit(1)
        print(f"{args.out} is up to date")
        return
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
